name: masamune_localize
description: >-
  Library that provides the translation function of Masamune framework.
  Manage translation data with Google SpreadSheet.
version: 0.2.8
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune_localize

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Data
  intl: ^0.16.1
  csv: ^4.0.3
  # Device
  flutter_device_locale: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Masamune
  masamune_test: ^0.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
